<?php

namespace App\Features\Chat\Services;

use App\Enums\MessageType;
use App\Features\Chat\Events\MessageSent;
use App\Features\Chat\Events\MessageUpdated;
use App\Features\Chat\Events\TypingStatusChanged;
use App\Features\Chat\Repositories\ConversationRepository;
use App\Features\Chat\Repositories\MessageRepository;
use App\Features\Friends\Services\FriendshipService;
use App\Features\Notifications\Services\FirebaseNotificationService;
use App\Models\Conversation;
use App\Models\Message;
use App\Models\TypingIndicator;
use App\Models\User;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;

class ChatService
{
    public function __construct(
        private readonly ConversationRepository $conversations,
        private readonly MessageRepository $messages,
        private readonly FriendshipService $friendships,
        private readonly FirebaseNotificationService $notifications,
    ) {
    }

    public function conversations(User $user, int $perPage): LengthAwarePaginator
    {
        return $this->conversations->forUser($user, $perPage);
    }

    public function startConversation(User $user, User $friend): Conversation
    {
        if (! $this->friendships->areFriends($user, $friend)) {
            throw ValidationException::withMessages(['user_id' => __('messages.only_friends_can_chat')]);
        }

        return $this->conversations->firstOrCreate($user, $friend)->load(['userOne', 'userTwo', 'lastMessage.conversation', 'lastMessage.sender']);
    }

    public function messages(User $user, int $conversationId, int $perPage): LengthAwarePaginator
    {
        $conversation = $this->conversations->findForUser($user, $conversationId);

        return $this->messages->paginate($conversation, $perPage);
    }

    public function send(User $user, int $conversationId, array $data): Message
    {
        return DB::transaction(function () use ($user, $conversationId, $data) {
            $conversation = $this->conversations->findForUser($user, $conversationId);
            $friend = $conversation->otherUser($user);

            if (! $this->friendships->areFriends($user, $friend)) {
                throw ValidationException::withMessages(['conversation_id' => __('messages.only_friends_can_chat')]);
            }

            $this->ensurePublicKeysExist($user, $friend);

            $payload = [
                'type' => $data['type'] ?? MessageType::Text->value,
                // Security boundary: ciphertext and nonce are generated by Flutter.
                // The backend stores and broadcasts them without decrypting or rewriting.
                'ciphertext' => $data['ciphertext'],
                'nonce' => $data['nonce'],
                'key_id' => $data['key_id'] ?? null,
                'encryption_version' => $data['encryption_version'],
                'reply_to_message_id' => $data['reply_to_message_id'] ?? null,
            ];

            if (($data['attachment'] ?? null) instanceof UploadedFile) {
                $attachment = $data['attachment'];

                $payload['attachment_path'] = $attachment->store('messages/attachments', 'public');
                $payload['attachment_name'] = null;
                $payload['attachment_mime'] = 'application/octet-stream';
                $payload['attachment_size'] = $attachment->getSize();
                $payload['attachment_duration_seconds'] = $data['duration_seconds'] ?? null;
            }

            if (($payload['reply_to_message_id'] ?? null) && ! $conversation->messages()->whereKey($payload['reply_to_message_id'])->exists()) {
                throw ValidationException::withMessages(['reply_to_message_id' => __('messages.message_not_found')]);
            }

            $message = $this->messages->create($conversation, $user, $payload)->load(['conversation', 'sender', 'replyTo.sender', 'replyTo.conversation']);
            $conversation->update(['latest_message_at' => $message->created_at]);

            broadcast(new MessageSent($message))->toOthers();
            $this->notifications->sendToUser(
                $friend,
                $user->full_name ?: $user->username ?: 'New message',
                $this->messageNotificationBody($message),
                [
                    'type' => 'message.sent',
                    'conversation_id' => $conversation->id,
                    'message_id' => $message->id,
                    'sender_id' => $user->id,
                ]
            );

            return $message;
        });
    }

    public function edit(User $user, int $conversationId, int $messageId, array $data): Message
    {
        return DB::transaction(function () use ($user, $conversationId, $messageId, $data) {
            $conversation = $this->conversations->findForUser($user, $conversationId);
            $message = $this->messages->findForConversation($conversation, $messageId);

            if ($message->sender_id !== $user->id) {
                throw ValidationException::withMessages(['message_id' => __('messages.message_action_not_allowed')]);
            }

            $message->update([
                'ciphertext' => $data['ciphertext'],
                'nonce' => $data['nonce'],
                'key_id' => $data['key_id'] ?? null,
                'encryption_version' => $data['encryption_version'],
                'edited_at' => now(),
            ]);
            $message = $message->refresh()->load(['conversation', 'sender', 'replyTo.sender', 'replyTo.conversation']);
            broadcast(new MessageUpdated($message, 'message.edited'))->toOthers();
            $this->notifications->sendToUser(
                $conversation->otherUser($user),
                'Message edited',
                ($user->full_name ?: $user->username ?: 'Someone') . ' edited a message',
                [
                    'type' => 'message.edited',
                    'conversation_id' => $conversation->id,
                    'message_id' => $message->id,
                    'sender_id' => $user->id,
                ]
            );

            return $message;
        });
    }

    public function delete(User $user, int $conversationId, int $messageId): void
    {
        DB::transaction(function () use ($user, $conversationId, $messageId) {
            $conversation = $this->conversations->findForUser($user, $conversationId);
            $message = $this->messages->findForConversation($conversation, $messageId);

            if ($message->sender_id !== $user->id) {
                throw ValidationException::withMessages(['message_id' => __('messages.message_action_not_allowed')]);
            }

            if ($message->attachment_path) {
                Storage::disk('public')->delete($message->attachment_path);
            }

            $message->delete();
            broadcast(new MessageUpdated($message, 'message.deleted'))->toOthers();
            $this->notifications->sendToUser(
                $conversation->otherUser($user),
                'Message deleted',
                ($user->full_name ?: $user->username ?: 'Someone') . ' deleted a message',
                [
                    'type' => 'message.deleted',
                    'conversation_id' => $conversation->id,
                    'message_id' => $message->id,
                    'sender_id' => $user->id,
                ]
            );
        });
    }

    public function markDelivered(User $user, int $conversationId, int $messageId): Message
    {
        return $this->markMessageTimestamp($user, $conversationId, $messageId, 'delivered_at', 'message.delivered');
    }

    public function markSeen(User $user, int $conversationId, int $messageId): Message
    {
        return $this->markMessageTimestamp($user, $conversationId, $messageId, 'seen_at', 'message.seen');
    }

    public function typing(User $user, int $conversationId, bool $isTyping): TypingIndicator
    {
        $conversation = $this->conversations->findForUser($user, $conversationId);

        $typing = TypingIndicator::updateOrCreate(
            ['conversation_id' => $conversation->id, 'user_id' => $user->id],
            ['is_typing' => $isTyping, 'updated_at' => now()]
        );

        broadcast(new TypingStatusChanged($typing))->toOthers();

        return $typing;
    }

    private function markMessageTimestamp(User $user, int $conversationId, int $messageId, string $column, string $event): Message
    {
        return DB::transaction(function () use ($user, $conversationId, $messageId, $column, $event) {
            $conversation = $this->conversations->findForUser($user, $conversationId);
            $message = $this->messages->findForConversation($conversation, $messageId);

            if ($message->sender_id === $user->id) {
                throw ValidationException::withMessages(['message_id' => __('messages.message_action_not_allowed')]);
            }

            if (! $message->{$column}) {
                $message->update([$column => now()]);
            }

            $message = $message->refresh()->load(['conversation', 'sender', 'replyTo.sender', 'replyTo.conversation']);
            broadcast(new MessageUpdated($message, $event))->toOthers();

            return $message;
        });
    }

    private function messageNotificationBody(Message $message): string
    {
        return 'Sent an encrypted message';
    }

    private function ensurePublicKeysExist(User $sender, User $receiver): void
    {
        if (! $sender->public_key) {
            throw ValidationException::withMessages(['public_key' => __('validation.required', ['attribute' => 'public key'])]);
        }

        if (! $receiver->public_key) {
            throw ValidationException::withMessages(['recipient_public_key' => __('validation.required', ['attribute' => 'recipient public key'])]);
        }
    }
}
